version: '3.8'
volumes:
  cache:
    driver: local
services:
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /etc/redis/redis.conf
    volumes: 
      - cache:/data
      - ./redis.conf:/etc/redis/redis.conf
